ALTER TABLE public.winamax_matches
ADD COLUMN IF NOT EXISTS score TEXT;

CREATE TABLE IF NOT EXISTS public.match_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.winamax_match_tags (
    match_id BIGINT NOT NULL REFERENCES public.winamax_matches(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES public.match_tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (match_id, tag_id)
);

ALTER TABLE public.match_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.winamax_match_tags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON public.match_tags;
CREATE POLICY "Allow public read access"
ON public.match_tags
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Allow public read access" ON public.winamax_match_tags;
CREATE POLICY "Allow public read access"
ON public.winamax_match_tags
FOR SELECT
USING (true);

INSERT INTO public.match_tags (code, label, description)
VALUES ('SIEGE', 'Siege', 'Score 0-0 and favorite odd dropped by at least 0.10 in less than 5 minutes.')
ON CONFLICT (code) DO NOTHING;
